name: HTML5 Validator

on: [pull_request, push]

jobs:
  validating:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HTML5Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: html5/
          blacklist: invalid
